---

- debug:
    msg: "imported RedHat/generic/disable-abrt-ccpp.yml"

- name: Check if package abrt-addon-ccpp is installed
  package:
    name: abrt-addon-ccpp
    state: present
  check_mode: true
  register: abrt_ccpp_check
  ignore_errors: yes
- debug:
    var: abrt_ccpp_check

- name: Disable abrt-ccpp if installed, and get status of abrtd
  block:
    - name: Disable abrt-ccpp if installed
      systemd:
        name: abrt-ccpp
        state: stopped
        enabled: no
      when: not abrt_ccpp_check.changed

    - name: Collect facts about system services
      service_facts:
      register: services_state

    - name: Get status of abrt-ccpp
      debug:
        msg: >
             abrt-ccpp is
             '{{ services_state.ansible_facts.services["abrt-ccpp.service"].state }}'
             and
             '{{ services_state.ansible_facts.services["abrt-ccpp.service"].status }}'
  when: not abrt_ccpp_check.changed

...
