---

- debug:
    msg: "imported RedHat/generic/configure-firewall.yml"

- name: Stop and disable service firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in ansible_facts.packages"

- name: Collect facts about system services
  service_facts:
  register: services_state

- name: Get status of firewalld
  debug:
    msg: >
         firewalld is
         '{{ services_state.ansible_facts.services["firewalld.service"].state }}'
         and
         '{{ services_state.ansible_facts.services["firewalld.service"].status }}'
...
