---

- debug:
    msg: "imported RedHat/generic/disable-abrt.yml"

- name: Check if abrt is installed
  package:
    name: abrt
    state: present
  check_mode: true
  register: abrt_check
  ignore_errors: yes
- debug:
    var: abrt_check

- name: Disable abrtd if installed, and get status of abrtd
  block:
    - name: Disable abrtd if installed
      systemd:
        name: abrtd
        state: stopped
        enabled: no
      when: not abrt_check.changed

    - name: Collect facts about system services
      service_facts:
      register: services_state

    - name: Get status of abrtd
      debug:
        msg: >
             abrtd is
             '{{ services_state.ansible_facts.services["abrtd.service"].state }}'
             and
             '{{ services_state.ansible_facts.services["abrtd.service"].status }}'
  when: not abrt_check.changed

...
