---

- debug:
    msg: "imported RedHat/generic/turn-off-auto-numa-balancing.yml"

# can be configured by tuned profile sap-hana, entry "kernel.numa_balancing = 0"
- block:
    - name: Check if numad is installed
      package:
        name: numad
        state: present
      check_mode: true
      register: numad_check
      ignore_errors: yes
    - debug:
        var: numad_check

    - name: Disable numad if installed, and get status of numad
      block:
        - name: Disable numad if installed
          systemd:
            name: numad
            state: stopped
            enabled: no
          when: not numad_check.changed

    - name: Collect facts about system services
      service_facts:
      register: services_state

    - name: Get status of numad
      debug:
        msg: >
             numad is
             '{{ services_state.ansible_facts.services["numad.service"].state }}'
             and
             '{{ services_state.ansible_facts.services["numad.service"].status }}'
      when: not numad_check.changed

  when:
    - not sap_hana_preconfigure_use_tuned_where_possible

...
